language: java

jdk:
  - oraclejdk8

before_install:
  - curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
  - sudo apt-get install -y nodejs

notifications:
  slack:
    rooms:
      - algalon:0VFlFf3fc108NULhyzjAp4pg#vivid
  email: false