language: java

jdk:
  - oraclejdk8

before_install:
  - curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
  - sudo apt-get install -y nodejs
  - psql -c 'create database vivid;' -U postgres
  - psql vivid -c 'create user vivid;'
  - psql vivid -c 'grant all privileges on database vivid to vivid;'
  - psql vivid -c 'alter schema public owner to vivid;'

notifications:
  slack:
    rooms:
      - algalon:0VFlFf3fc108NULhyzjAp4pg#vivid
  email: false