app:
  version: de4db33f
################### DataSource Configuration ##########################

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/vivid
  username: vivid
  password: vivid

init-db: false

################### Hibernate Configuration ##########################

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: update